name = "Yump"
author = "BOOM"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "622b68b4b6b57cd297cbd3a714aef74ea047ca0289d3e3bc3bafb1291324d40e"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
