name = "Yump"
author = "BOOM"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a45ae039995742c00ea9bc5a1ee32c52d68dcff88af86e784821cd3c642bdc0"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
