name = "Yump"
author = "BOOM"
version = "1.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24abecfed443361c5a5dadf7ba40a8e1464cd6000e0a3f39fcad57fcbbb18841"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
